### ISSUE TITLE
Issues with cluster set up

### ISSUE THREAD

**Issue by gohilankit** [amritbhanu/Spark_VCL#1]
I observed several issues while setting up the cluster, particularly with HDFS set up
- [x] .bashrc file is not getting generated correctly:
       1. Missing a closing fi statement for the last if struct
       2. $HADOOP_INSTALL is getting generated with a hard-coded username
- [x] Configuration missing in Hadoop configuration files on slave nodes.
     For example, hdfs-site.xml should contain the IP of name node for communicating with other nodes, but it was empty. There were others as well.

As a result, we are not getting a single consolidated DFS but multiple isolated filesystems.

**Comment by amritbhanu** [comment]
For the 1st issue, it should work as you had an old rep at your local machine.

for the 2nd issue, our current setup we dont need anything configured on slave node. Slave nodes need all those configurations when we are using hadoop map -reduce scripts or code. Here we are just using distributed file system to store files which is working properly. Spark will do the map reduce part which is configured properly.

**Comment by amritbhanu** [comment]
@gohilankit Can you run the updated code and verify all these issues are solved? And also I tried running 

```
hadoop dfsadmin -report
```

But i dont see any distributed file structure. Can you fix this? And let me know what is missing in the configs.

**Comment by amritbhanu** [comment]
Solved the above 2 issues, as well as done with the setup of hdfs properly. So now I can see distributed files having a storage of 1 TB with 45 nodes.
- [ ] Can you try to load the dataset directly on hdfs rather on a single node?

**Comment by gohilankit** [comment]
Resolved.
